# Generated by Django 4.1.1 on 2022-11-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.BigIntegerField(default=0)),
                ('state', models.CharField(choices=[('kerala', 'kerala'), ('demo', 'demo'), ('None', 'None')], default='kerala', max_length=100)),
                ('district', models.CharField(choices=[('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Kannur', 'Kannur'), ('Trivandrum', 'Trivandrum'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Kollam', 'Kollam'), ('Ernakulam', 'Ernakulam'), ('Wayanad', 'Wayanad'), ('Kasaragod', 'Kasaragod'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('None', 'None')], default='None', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('land_mark', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField(default=0)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('is_customer', 'is_customer'), ('is_admin', 'is_admin'), ('is_superadmin', 'is_superadmin'), ('None', 'None')], max_length=100)),
                ('status', models.CharField(default='Completed', max_length=40)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
