# Generated by Django 5.0.2 on 2024-03-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_driverreg',
            field=models.BooleanField(default=False),
        ),
    ]
