# Generated by Django 5.0.2 on 2024-03-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_driverreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('is_customer', 'is_customer'), ('is_admin', 'is_admin'), ('is_superadmin', 'is_superadmin'), ('is_driverreg', 'is_driverreg')], max_length=100),
        ),
    ]
