# Generated by Django 4.1.1 on 2022-11-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bin_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_color', models.CharField(max_length=100)),
                ('bin_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='complaintpost',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_landmark', models.CharField(max_length=100)),
                ('bin_number', models.CharField(max_length=100)),
                ('c_complant', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(default='', max_length=100)),
                ('emp_address', models.CharField(max_length=200)),
                ('emp_email', models.CharField(max_length=100, unique=True)),
                ('emp_phone', models.BigIntegerField()),
                ('emp_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('register_no', models.CharField(max_length=100)),
                ('regd_owner', models.CharField(max_length=100)),
                ('reg_address', models.CharField(max_length=100)),
                ('makers_class', models.CharField(max_length=100)),
                ('vehicle_class', models.CharField(max_length=100)),
                ('fuel', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('insurance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('employee_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.employee', verbose_name='emp_name')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_address', models.CharField(max_length=200)),
                ('driver_email', models.CharField(max_length=100, unique=True)),
                ('driver_phone', models.BigIntegerField()),
                ('driver_licence', models.CharField(max_length=100)),
                ('driver_image', models.ImageField(upload_to='')),
                ('driver_location', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.location', verbose_name=' region')),
                ('driver_vehicle', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.vehicle', verbose_name='register_no')),
            ],
        ),
    ]
