# Generated by Django 4.1.1 on 2022-11-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_bins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bins',
            new_name='bin',
        ),
    ]
