# Generated by Django 4.1.1 on 2022-11-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_bins_bin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bin',
            new_name='Bins',
        ),
    ]
