# Generated by Django 4.1.1 on 2022-11-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_bin_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Allocatted_bin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.bins', verbose_name='Bin_name'),
        ),
    ]
