# Generated by Django 4.1.1 on 2022-11-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_driver_allocatted_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleingday',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
            ],
        ),
    ]
