# Generated by Django 4.1.1 on 2022-11-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_scheduleingday'),
    ]

    operations = [
        migrations.AddField(
            model_name='bins',
            name='collections_day',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.scheduleingday', verbose_name='day'),
        ),
    ]
