# Generated by Django 4.1.1 on 2022-11-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_bins_collections_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Allocatted_bin',
        ),
        migrations.DeleteModel(
            name='Bins',
        ),
    ]
