# Generated by Django 4.1.1 on 2022-11-20 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_bins_driver_allocatted_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='workupdation',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.TimeField(default=0)),
                ('Date', models.DateField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('Bin_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.bins', verbose_name='Bin_name')),
                ('Driver_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.driver', verbose_name='driver_name')),
                ('Location', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.location', verbose_name='region')),
            ],
        ),
    ]
