# Generated by Django 4.1.1 on 2022-11-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_driver_allocatted_bin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Allocatted_direction',
        ),
        migrations.AddField(
            model_name='driver',
            name='Allocatted_bin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.bins', verbose_name='Bin_name'),
        ),
    ]
