# Generated by Django 4.1.1 on 2022-11-22 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_remove_driver_allocatted_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Allocated_direction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.scheduleingday', verbose_name='direction'),
        ),
    ]
