# Generated by Django 4.1.1 on 2022-11-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_driver_allocated_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Allocated_direction',
        ),
        migrations.AddField(
            model_name='driver',
            name='Allocated_day',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='Home.scheduleingday', verbose_name='day'),
        ),
    ]
