# Generated by Django 4.1.1 on 2022-11-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_remove_driver_allocated_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Allocated_day',
        ),
    ]
