# Generated by Django 5.0.2 on 2024-03-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_remove_driver_allocated_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='employee_name',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
