# Generated by Django 5.0.2 on 2024-03-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_complaintpost_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintpost',
            name='name',
        ),
    ]
