# Generated by Django 5.0.2 on 2024-03-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_alter_driver_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workupdation',
            old_name='Driver_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='complaintpost',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
