# Generated by Django 5.0.2 on 2024-03-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_rename_driver_name_workupdation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintpost',
            name='c_complant',
            field=models.TextField(max_length=500),
        ),
    ]
