# Generated by Django 5.0.2 on 2024-03-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_alter_complaintpost_c_complant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bins',
            name='Bin_address2',
        ),
        migrations.RemoveField(
            model_name='bins',
            name='Bin_address3',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
    ]
