# Generated by Django 5.0.2 on 2024-03-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_remove_bins_bin_address2_remove_bins_bin_address3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintpost',
            name='bin_number',
        ),
        migrations.AddField(
            model_name='bins',
            name='allocated_driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.driver', verbose_name='Allocated Driver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaintpost',
            name='bin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Home.bins'),
            preserve_default=False,
        ),
    ]
