# Generated by Django 5.0.2 on 2024-03-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_remove_complaintpost_bin_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Allocatted_bin',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.bins', verbose_name='Bin_name'),
        ),
    ]
