# Generated by Django 5.0.2 on 2024-03-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_alter_driver_allocatted_bin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bins',
            name='Bin_date',
        ),
        migrations.RemoveField(
            model_name='bins',
            name='distance_KM',
        ),
        migrations.RemoveField(
            model_name='bins',
            name='total_time',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Allocatted_bin',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='reg_address',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='regd_owner',
        ),
    ]
