# Generated by Django 5.0.2 on 2024-03-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0030_remove_bins_bin_date_remove_bins_distance_km_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workupdation',
        ),
    ]
